name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: rustup target add wasm32-unknown-unknown
    - run: cargo install trunk
    - run: wget 'https://github.com/daac-tools/vaporetto/releases/download/v0.5.0/bccwj-suw+unidic+tag.tar.xz'
    - run: tar xf ./bccwj-suw+unidic+tag.tar.xz
    - run: mv ./bccwj-suw+unidic+tag/bccwj-suw+unidic+tag.model.zst ./src/
    - run: trunk build --release --public-url vaporetto-demo
    - run: cp -r ./dist/ ./public/
    - uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
